// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.6
// source: CRUD.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age   uint32 `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	Email string `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_CRUD_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_CRUD_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_CRUD_proto_rawDescGZIP(), []int{0}
}

func (x *UserMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserMessage) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_CRUD_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_CRUD_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_CRUD_proto_rawDescGZIP(), []int{1}
}

func (x *ID) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_CRUD_proto protoreflect.FileDescriptor

var file_CRUD_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x43, 0x52, 0x55, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0b,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x41, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x32, 0x77, 0x0a,
	0x04, 0x43, 0x52, 0x55, 0x44, 0x12, 0x1d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x0c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x03, 0x2e,
	0x49, 0x44, 0x22, 0x00, 0x12, 0x1b, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x03, 0x2e, 0x49,
	0x44, 0x1a, 0x0c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x12, 0x1d, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x03, 0x2e, 0x49, 0x44, 0x22, 0x00,
	0x12, 0x14, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a,
	0x03, 0x2e, 0x49, 0x44, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_CRUD_proto_rawDescOnce sync.Once
	file_CRUD_proto_rawDescData = file_CRUD_proto_rawDesc
)

func file_CRUD_proto_rawDescGZIP() []byte {
	file_CRUD_proto_rawDescOnce.Do(func() {
		file_CRUD_proto_rawDescData = protoimpl.X.CompressGZIP(file_CRUD_proto_rawDescData)
	})
	return file_CRUD_proto_rawDescData
}

var file_CRUD_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CRUD_proto_goTypes = []any{
	(*UserMessage)(nil), // 0: UserMessage
	(*ID)(nil),          // 1: ID
}
var file_CRUD_proto_depIdxs = []int32{
	0, // 0: CRUD.Create:input_type -> UserMessage
	1, // 1: CRUD.Read:input_type -> ID
	0, // 2: CRUD.Update:input_type -> UserMessage
	1, // 3: CRUD.Delete:input_type -> ID
	1, // 4: CRUD.Create:output_type -> ID
	0, // 5: CRUD.Read:output_type -> UserMessage
	1, // 6: CRUD.Update:output_type -> ID
	1, // 7: CRUD.Delete:output_type -> ID
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CRUD_proto_init() }
func file_CRUD_proto_init() {
	if File_CRUD_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CRUD_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CRUD_proto_goTypes,
		DependencyIndexes: file_CRUD_proto_depIdxs,
		MessageInfos:      file_CRUD_proto_msgTypes,
	}.Build()
	File_CRUD_proto = out.File
	file_CRUD_proto_rawDesc = nil
	file_CRUD_proto_goTypes = nil
	file_CRUD_proto_depIdxs = nil
}
